## Server Configuration
SERVER_NAME: "whatsapp-rest"
SERVER_IP: "127.0.0.1"
SERVER_PORT: "3000"
SERVER_STORE_PATH: "./config/stores"
SERVER_UPLOAD_PATH: "./config/uploads"
SERVER_UPLOAD_LIMIT: 8
SERVER_LOG_LEVEL: "debug"

## Router Configuration
ROUTER_BASE_PATH: "/api"

# BASIC AUTH
AUTH_BASIC_USERNAME: "client"
AUTH_BASIC_PASSWORD: "secret"

# URL Hook
WEBHOOK_URL: "http://localhost:8000/whatsapp/callback"

## WhatsApp Configuration
WHATSAPP_CLIENT_VERSION_MAJOR: 2
WHATSAPP_CLIENT_VERSION_MINOR: 206
WHATSAPP_CLIENT_VERSION_BUILD: 24
